{
 "title": "HomeNetwork-Prom",
 "description": "HomeNetwork",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "DHCP Clients",
   "type": "table",
   "description": "DHCP Clients",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "uci_dhcp_host{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OpenWRT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1) /  count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "MEM Used",
   "type": "stat",
   "description": "MEM Used",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes"
    }
   ]
  },
  {
   "title": "Total NAT Traffic",
   "type": "stat",
   "description": "Total NAT traffic (WAN)",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(node_nat_traffic)" }
   ]
  },
  {
   "title": "Total Network Traffic Rx/Tx",
   "type": "stat",
   "description": "Total network traffic",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum(node_network_transmit_bytes_total) + sum(node_network_receive_bytes_total))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "description": "all connected clients",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "collectd_dhcpleases_count{}" }
   ]
  },
  {
   "title": "Interface Speed LAN,VPN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"wlan-sta0\"}[30s])",
     "legendFormat": "WAN Download"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"wlan-sta0\"}[30s])",
     "legendFormat": "WAN Upload"
    }
   ]
  },
  {
   "title": "Download Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(collectd_iptables_ipt_bytes_total{iptables=\"mangle-iptmon_tx\", type!=\"tx_binbootdatadevetcliblib64mntoverlayprocromrootsbinsystmpusrvarwww\"}[30s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upload Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(collectd_iptables_ipt_bytes_total{iptables=\"mangle-iptmon_rx\", type!=\"rx_binbootdatadevetcliblib64mntoverlayprocromrootsbinsystmpusrvarwww\"}[30s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ping (5m)",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "collectd_ping{ping=~\"1\\\\.1\\\\.1\\\\.1|8\\\\.8\\\\.8\\\\.8\"}",
     "legendFormat": "{{ping}}"
    }
   ]
  },
  {
   "title": "ping (5m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "collectd_ping{ping=~\"1\\\\.1\\\\.1\\\\.1|8\\\\.8\\\\.8\\\\.8\"}",
     "legendFormat": "{{ping}}"
    }
   ]
  },
  {
   "title": "Hourly Traffic Download",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_packets_total{device=\"wlan1\"}[1h])",
     "legendFormat": "WAN Download"
    }
   ]
  },
  {
   "title": "Hourly Traffic Upload",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_packets_total{device=\"wlan1\"}[1h])",
     "legendFormat": "WAN Upload"
    }
   ]
  },
  {
   "title": "7dayTraffic Sent",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_packets_total{device=\"wlan1\"}[1d])",
     "legendFormat": "{{device}} -Sent"
    }
   ]
  },
  {
   "title": "Top 10 NAT Traffic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, node_nat_traffic /1024/1024)",
     "legendFormat": "SRC= {{src}} -> Dest= {{dest}}"
    }
   ]
  },
  {
   "title": "Top 10 NAT Traffic",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "topk(10, node_nat_traffic /1024/1024)",
     "legendFormat": "Src= {{src}} -> Dest= {{dest}}"
    }
   ]
  },
  {
   "title": "Transmit Packets Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_transmit_packets_total{device=~\"br-lan|eth0|wlan0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=~\"br-lan|eth0|wlan0\"} /1024/1024",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}