{
 "title": "OpenWRT-Dashboard",
 "description": "HomeNetwork",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(type)" } },
   { "name": "srcip", "label": "srcip", "query": { "query": "label_values(src)" } }
  ]
 },
 "panels": [
  { "title": "Network Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Health",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "collectd_ping{ping=~\"1\\\\.1\\\\.1\\\\.1\"}",
     "legendFormat": "{{ping}}"
    }
   ]
  },
  {
   "title": "SpeedTest",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "speedtest_download_bytes{}", "legendFormat": "Download Speed" },
    { "expr": "speedtest_upload_bytes{}", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Jitter/latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_jittter_seconds", "legendFormat": "Jitter" },
    { "expr": "speedtest_latency_seconds", "legendFormat": "latency" }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_running" }
   ]
  },
  {
   "title": "Protection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_protection_enabled" }
   ]
  },
  {
   "title": "Number of queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_num_dns_queries" }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_num_blocked_filtering" }
   ]
  },
  {
   "title": "Percent of ads blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering / adguard_num_dns_queries * 100"
    }
   ]
  },
  {
   "title": "Processing TIme",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_avg_processing_time", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "title": "Top clients",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "adguard_top_clients{}", "legendFormat": "{{ client }}" }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(adguard_top_blocked_domains) by (domain)",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "OpenWRT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DHCP Clients",
   "type": "table",
   "description": "DHCP Clients",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "uci_dhcp_host{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1) /  count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "description": "RAM Used",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes"
    }
   ]
  },
  {
   "title": "Total NAT Traffic",
   "type": "stat",
   "description": "Total NAT traffic (WAN)",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(node_nat_traffic)" }
   ]
  },
  {
   "title": "Total Network Traffic Rx/Tx",
   "type": "stat",
   "description": "Total network traffic",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum(node_network_transmit_bytes_total) + sum(node_network_receive_bytes_total))"
    }
   ]
  },
  {
   "title": "DHCP Clients",
   "type": "stat",
   "description": "DHCP Clients",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(uci_dhcp_host{})" }
   ]
  },
  {
   "title": "Interface Speed WAN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"wlan-sta0\"}[10s])",
     "legendFormat": "WAN Download"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"wlan-sta0\"}[10s])",
     "legendFormat": "WAN Upload"
    }
   ]
  },
  {
   "title": "Download Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(collectd_iptables_ipt_bytes_total{iptables=\"mangle-iptmon_tx\", type=~\"tx_$hostname\"}[10s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upload Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(collectd_iptables_ipt_bytes_total{iptables=\"mangle-iptmon_rx\", type=~\"rx_$hostname\"}[10s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ping (5m)",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "collectd_ping{ping=~\"1\\\\.1\\\\.1\\\\.1|8\\\\.8\\\\.8\\\\.8\"}",
     "legendFormat": "{{ping}}"
    }
   ]
  },
  {
   "title": "ping (5m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "collectd_ping{ping=~\"1\\\\.1\\\\.1\\\\.1|8\\\\.8\\\\.8\\\\.8\"}",
     "legendFormat": "{{ping}}"
    }
   ]
  },
  {
   "title": "Hourly Traffic Download",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{device=\"wlan-sta0\"}[1h])",
     "legendFormat": "WAN Download"
    }
   ]
  },
  {
   "title": "Hourly Traffic Upload",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total{device=\"wlan-sta0\"}[1h])",
     "legendFormat": "WAN Upload"
    }
   ]
  },
  {
   "title": "7dayTraffic Downloaded",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{device=\"wlan-sta0\"}[1d])",
     "legendFormat": "{{device}} -Sent"
    }
   ]
  },
  {
   "title": "7dayTraffic Uploaded",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total{device=\"wlan-sta0\"}[1d])",
     "legendFormat": "{{device}} -Sent"
    }
   ]
  },
  {
   "title": "NAT Traffic",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(node_nat_traffic{src=~\"$srcip\",dest!=\"10.0.5.1\",dport!=\"53\",dport!=\"53\"} /1024/1024)",
     "legendFormat": "Dest {{dest}} ->  SRC {{src}}"
    }
   ]
  },
  {
   "title": "Dest IP Count ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (dest) (count_over_time(node_nat_traffic{dport!=\"53\",dport!=\"9100\"}[$__range]))",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "Port Count ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (dport) (count_over_time(node_nat_traffic{dport!=\"53\",dport!=\"9100\"}[$__range]))",
     "legendFormat": "Port {{dport}}"
    }
   ]
  }
 ]
}