{
 "title": "OpenWRT-Dashboard",
 "description": "HomeNetwork",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Router Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Internet Connection",
   "type": "stat",
   "description": "Internet Connection is based on a ping data from CollectD against 1.1.1.1. \nIf the ping is higher than 50ms, it will turn yellow-ish. If its over 100ms, it will turn red. ",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collectd_ping{ping=\"1.1.1.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAN IP",
   "type": "table",
   "description": "WAN IP data is gathered via the 1-min-script. it will curl a public site to get the Public IP. The WAN IP is gathered locally from WRT. It is then outputted to a file in /tmp/wanip.out. \n\nhttps://github.com/benisai/Openwrt-Monitoring/blob/main/Router/scripts/1-minute-script.sh",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "targets": [
    { "expr": "wan_info{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(uci_dhcp_host{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature and Fan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_temp{}", "legendFormat": "Temp ℃" },
    { "expr": "router_fan_speed{}", "legendFormat": "Fan Speed (RPM)" }
   ]
  },
  { "title": "Network Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Network Health",
   "type": "status-history",
   "description": "Network Health is based on a ping data from CollectD against 1.1.1.1. \nIf the ping is higher than 50ms, it will turn yellow-ish. If its over 100ms, it will turn red. ",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "collectd_ping{ping=~\"1\\\\.1\\\\.1\\\\.1\"}",
     "legendFormat": "{{ping}}"
    }
   ]
  },
  {
   "title": "SpeedTest",
   "type": "timeseries",
   "description": "SpeedTest data is gathered from the speedtest.sh script. It is then outputted to /tmp/speedtest.out file for Prometheus to collect. If there is no data from the script, more than likely the testhost (netperf.bufferbloat.net) blocked you from attempting speedtests, try again in a few hours. \n\nhttps://github.com/benisai/Openwrt-Monitoring/blob/main/Router/scripts/speedtest.sh",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "router_speedtest_download{}", "legendFormat": "Download Speed" },
    { "expr": "router_speedtest_upload{}", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "SpeedTest",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_speedtest_download{}", "legendFormat": "Download:" },
    { "expr": "router_speedtest_upload{}", "legendFormat": "Upload:" }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "barchart",
   "description": "PacketLoss data is based on ping data collected via the 1-min-script.sh. It will ping 1.1.1.1  20 times and the script will record any packet drops. \n\nhttps://github.com/benisai/Openwrt-Monitoring/blob/main/Router/scripts/1-minute-script.sh",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "packet_loss{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Active Connection Count",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nf_conntrack_entries{}", "legendFormat": "Connections" }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_running" }
   ]
  },
  {
   "title": "Protection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_protection_enabled" }
   ]
  },
  {
   "title": "Number of queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_num_dns_queries" }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_num_blocked_filtering" }
   ]
  },
  {
   "title": "Percent of ads blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering / adguard_num_dns_queries * 100"
    }
   ]
  },
  {
   "title": "Processing TIme",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_avg_processing_time", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "title": "Top clients",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "adguard_top_clients{}", "legendFormat": "{{ client }}" }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(adguard_top_blocked_domains) by (domain)",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "OpenWRT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "description": "/usr/bin/device-status-ping.sh script will ping IP Addr in /tmp/dhcp.lease file. \nThe device-status-ping.sh script will run every minute via crontab and output a file to tmp/device-status.out\n\nSome devices dont respond to pings, I dont know why. \n\n\nhttps://github.com/benisai/Openwrt-Monitoring/blob/main/Router/scripts/device-status-ping.sh",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    { "expr": "router_device_status{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1) /  count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "description": "RAM Used",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes"
    }
   ]
  },
  {
   "title": "Total NAT Traffic",
   "type": "stat",
   "description": "Total NAT traffic (WAN)",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(node_nat_traffic)" }
   ]
  },
  {
   "title": "Total Network Traffic Rx/Tx",
   "type": "stat",
   "description": "Total network traffic",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(sum(node_network_transmit_bytes_total{device=\"wlan-sta0\"}) + sum(node_network_receive_bytes_total{device=\"wlan-sta0\"})/1024/1024)"
    }
   ]
  },
  {
   "title": "DHCP Clients",
   "type": "stat",
   "description": "DHCP Clients",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(uci_dhcp_host{})" }
   ]
  },
  {
   "title": "Bandwidth Usage - 150GB Cap",
   "type": "bargauge",
   "description": "Bandwidth Usage Provided by Vnstat2. The 1-min-script.sh will parse and output a file to /tmp/monthoutput.out for Prometheus to scrape.  \n\n\n\nThe cap is set in this panel:\nMax\nLeave empty to calculate based on all values\n\n\nhttps://github.com/benisai/Openwrt-Monitoring/blob/main/Router/scripts/1-minute-script.sh",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(router_vnstat_month_download{}) + sum(router_vnstat_month_upload{})"
    }
   ]
  },
  {
   "title": "12h Traffic",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{device=\"wlan-sta0\"}[12h])",
     "legendFormat": "WAN Download"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{device=\"wlan-sta0\"}[12h])",
     "legendFormat": "WAN Upload"
    }
   ]
  },
  {
   "title": "Interface Speed WAN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"wlan-sta0\"}[10s])",
     "legendFormat": "WAN Download"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"wlan-sta0\"}[10s])",
     "legendFormat": "WAN Upload"
    }
   ]
  },
  {
   "title": "Live Download Traffic",
   "type": "timeseries",
   "description": "This live traffic data is created by IPTmon. It is gathered via CollectD.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(collectd_iptables_ipt_bytes_total{iptables=\"mangle-iptmon_tx\"}[10s])/2",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Live Upload Traffic",
   "type": "timeseries",
   "description": "This live traffic data is created by IPTmon. It is gathered via CollectD.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(collectd_iptables_ipt_bytes_total{iptables=\"mangle-iptmon_rx\"}[10s])/2",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Download Traffic Last 2h",
   "type": "bargauge",
   "description": "This data is created by IPTmon. It is gathered via CollectD.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(collectd_iptables_ipt_bytes_total{iptables=\"mangle-iptmon_tx\"}[2h])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Uploaded Traffic Last 2h",
   "type": "bargauge",
   "description": "This data is created by IPTmon. It is gathered via CollectD.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(collectd_iptables_ipt_bytes_total{iptables=\"mangle-iptmon_rx\"}[2h])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ping (5m)",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "collectd_ping{ping=~\"1\\\\.1\\\\.1\\\\.1|9\\\\.9\\\\.9\\\\.9\"}",
     "legendFormat": "{{ping}}"
    }
   ]
  },
  {
   "title": "ping (5m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "collectd_ping{ping=~\"1\\\\.1\\\\.1\\\\.1|9\\\\.9\\\\.9\\\\.9\"}",
     "legendFormat": "{{ping}}"
    }
   ]
  },
  {
   "title": "Hourly Traffic",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{device=\"wlan-sta0\"}[1h])",
     "legendFormat": "WAN Download"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{device=\"wlan-sta0\"}[1h])",
     "legendFormat": "WAN Upload"
    }
   ]
  },
  {
   "title": "7dayTraffic",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{device=\"wlan-sta0\"}[1d])",
     "legendFormat": "WAN Download"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{device=\"wlan-sta0\"}[1d])",
     "legendFormat": "WAN Upload"
    }
   ]
  },
  {
   "title": "NAT Traffic",
   "type": "table",
   "description": "You can define src and dest names in the overrides section. I left some examples. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(node_nat_traffic{dest!=\"10.0.5.1\",dport!=\"53\",dport!=\"53\"} /1024/1024)",
     "legendFormat": "Dest {{dest}} ->  SRC {{src}}"
    }
   ]
  },
  {
   "title": "New Devices Connected Last 24hrs",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "router_new_device{}", "legendFormat": "Dest {{dest}} ->  SRC {{src}}" }
   ]
  },
  {
   "title": "Dest IP Count ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (dest) (count_over_time(node_nat_traffic{dport!=\"53\",dport!=\"9100\"}[$__range]))",
     "legendFormat": "{{dest}}"
    }
   ]
  },
  {
   "title": "Dest Port Count ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (dport) (count_over_time(node_nat_traffic{dport!=\"53\",dport!=\"9100\"}[$__range]))",
     "legendFormat": "Port {{dport}}"
    }
   ]
  },
  {
   "title": "Top IP Last 1h",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (dest) (count_over_time(node_nat_traffic{dport!=\"53\",dport!=\"9100\"}[1h]))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}