server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://lokimiddleware:3100/loki/api/v1/push


scrape_configs:
  - job_name: netify
    static_configs:
    - targets:
        - localhost
      labels:
        job: netifylogs
        __path__: /var/log/netify/*log
    pipeline_stages:
      - json:
          expressions:
            detected_protocol_name: detected_protocol_name
            host_server_name: host_server_name
            local_ip: local_ip
            local_port: local_port
            other_ip: other_ip
            other_port: other_port
      - labels:
          host_server_name:
          detected_protocol_name:
          local_ip:
          local_port:
          other_ip:
          other_port:
      - template:
          source: output_msg
          template: 'host_server_name="{{ .host_server_name }}" detected_protocol_name="{{ .detected_protocol_name }}" local_ip="{{ .local_ip }}" local_port="{{ .local_port }}"  GeoIP_Source="{{.other_ip }}"  other_port="{{ .other_port }}"'

      - output:
          source: output_msg
