scrape_configs:
  - job_name: 'openwrt-prom'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.5.1:9100']
        labels:
          group: 'Router'

  - job_name: 'openwrt-collectd'
    scrape_interval: 5s
    static_configs:
      - targets: ['collectd-exp-home:9103']
        labels:
          group: 'owrt-collectd'

  - job_name: 'agh-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['agh-exporter-home:9617']

  #- job_name: 'speedtest'
  #  metrics_path: /probe
  #  params:
  #    script: [speedtest]
  #  static_configs:
  #    - targets:
  #      - Server:ip:6100
  #  scrape_interval: 60m
  #  scrape_timeout: 90s

  #- job_name: 'script_exporter'
  #  metrics_path: /metrics
  #  static_configs:
  #    - targets: ['HomeServer-IP-Address:6100']
        


